version: '2.1'

services:
  product:
    image: ms-demo-03-swagger-product-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  recommendation:
    image: ms-demo-03-swagger-recommendation-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  review:
    image: ms-demo-03-swagger-review-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  product-composite:
    image: ms-demo-03-swagger-product-composite-service:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
