server:
  port: 7000

app:
  product-service:
    host: localhost
    port: 7001
  recommendation-service:
    host: localhost
    port: 7002
  review-service:
    host: localhost
    port: 7003

logging:
  level:
    root: INFO
    jp.vmware.sol: DEBUG

api:
  common:
    version: 1.0.0
    title: 商品情報 API
    description: 商品、お薦め、レビューサービスの情報をまとめて返す商品情報サービスの API
    termsOfServiceUrl: MINE TERMS OF SERVICE URL
    license: License
    licenseUrl: MY LICENSE URL
    contact:
      name: お問い合わせ先
      url: My URL
      email: vmware@vcloud.local
  product-composite:
    get-composite-product:
      description: 指定した製品id の複合ビューを返す
      notes: |
        # 通常のレスポンス
        もし指定した製品idが見つかった場合、以下の情報を返す:
        1. 製品の基本情報
        1. レビュー
        1. お薦め
        1. サービスアドレス

        # 以下のケースでは部分的か結果を返す（テスト用）

        ## 製品id 113
        200 - OK, お薦めは返信されない

        ## 製品id 213
        200 - OK, レビューは返信されない

        ## 製品id 数字以外
        400 - Bad Request, エラーが返される

        ## 製品id 13
        404 - Not Found, エラーが返される

        ## 製品id 負数
        422 - Unprocessable Entity, エラーが返される

---
spring:
  config:
    activate:
      on-profile: docker

server:
  port: 8080

app:
  product-service:
    host: product
    port: 8080
  recommendation-service:
    host: recommendation
    port: 8080
  review-service:
    host: review
    port: 8080
